"""Case com informações fornecidas pelo autor; sem arquitetura presumida."""

DESCRIPTION = 'Projeto de MMORPG com backend desenvolvido integralmente em Python. Um case de desenvolvimento de jogos apresentado pela perspectiva da engenharia de software e da implementação de backend.'

VISUAL = '''<figure class="project-visual mmorpg-visual"><div class="visual-kicker">GAME DEVELOPMENT / BACKEND ENGINEERING</div><div class="game-wordmark">MMORPG<span>BACKEND EM PYTHON</span></div><div class="game-language"><span>PYTHON</span><span>DESENVOLVIMENTO DE JOGOS</span></div><figcaption>Identidade editorial do case · não representa uma captura do jogo</figcaption></figure>'''

CARD = '''<article class="project project-mmorpg" data-category="mmorpg">'''+VISUAL+'''<div class="project-body"><div class="card-top"><span class="eyebrow">06 / Python / Game Backend</span><span class="status">Projeto autoral</span></div><h3>MMORPG em Python</h3><p class="project-statement">Engenharia por trás do jogo.</p><p>Backend de um MMORPG desenvolvido integralmente em Python. Uma aplicação da linguagem ao desenvolvimento de jogos, ampliando os cases de APIs, automação e dados.</p><p class="stack">Python · Backend · Game Development</p><div class="card-links"><a href="cases.html#mmorpg">Conhecer o backend do jogo →</a></div></div></article>'''

CASE = '''<article class="case" id="mmorpg"><div class="case-heading"><div><p class="eyebrow">Python / Backend / Game Development</p><h2>MMORPG em Python</h2></div><span class="status">Projeto autoral</span></div><p class="intro">Engenharia por trás do jogo. Desenvolvimento de um MMORPG com toda a implementação de backend em Python.</p>'''+VISUAL+'''<div class="case-facts"><div><span>CONTRIBUIÇÃO INFORMADA</span><p>Desenvolvimento integral do backend do jogo em Python.</p></div><div><span>TECNOLOGIA CONFIRMADA PELO AUTOR</span><p>Python. Frameworks, banco de dados e infraestrutura ainda não documentados neste case.</p></div></div><dl><dt>O projeto</dt><dd>Um MMORPG autoral apresentado como trabalho de backend. O foco deste case é a implementação do software que sustenta o jogo, além da sua apresentação visual.</dd><dt>O papel no portfólio</dt><dd>Mostrar o uso de Python em desenvolvimento de jogos, complementando sua aplicação em automação operacional e análise de dados. O projeto amplia a narrativa de engenharia para um domínio diferente dos dashboards e aplicações web.</dd><dt>Escopo de autoria</dt><dd>O autor informa ter desenvolvido todo o backend em Python. Essa afirmação se refere ao backend; não implica que o cliente gráfico, a arte ou todas as demais partes do jogo tenham sido feitos na mesma linguagem.</dd><dt>Detalhamento técnico</dt><dd>O código e a documentação ainda não foram disponibilizados nesta revisão. A divisão de módulos, as regras do jogo, a persistência e a comunicação entre jogadores serão descritas a partir da implementação, sem presumir componentes pelo nome MMORPG.</dd></dl><div class="scope-note"><strong>Sobre as informações deste case</strong><p>Descrição baseada nas informações fornecidas pelo autor. Repositório, demonstração e estágio de desenvolvimento ainda não informados. Multiplayer, quantidade de jogadores simultâneos e infraestrutura não foram verificados.</p></div><a class="button" href="mailto:erickribeirogon@gmail.com?subject=Conhecer%20o%20MMORPG%20em%20Python">Conversar sobre o projeto ↗</a></article>'''
