"""Apresentação pública. A análise detalhada permanece no relatório técnico."""
from pathlib import Path
from html import escape as e
from mmorpg_case import CARD as MMORPG_CARD, CASE as MMORPG_CASE

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://github.com/ErickRibGo/'

NOTES = {
 'pvt': ('Interface → API → decisão', 'Regras de saúde calculadas no backend, contratos TypeScript e dados de demonstração em PostgreSQL.', 'MVP com seed de demonstração. Integração TOTVS RM e autenticação ainda não implementadas.'),
 'jungle': ('Um comando. Um efeito financeiro.', 'Locks e idempotência persistente para coordenar saldo, ledger e mensagens.', 'Case técnico executado em Bun, com infraestrutura local descrita no repositório. Autenticação ainda não implementada; testes não executados nesta revisão.'),
 'retail': ('Dados antes de conclusões.', '100.000 transações para investigar padrões e formular hipóteses de negócio.', 'Análise exploratória da base estudada. Não é um modelo preditivo nem comprovação de redução de fraude.'),
 'chat': ('Uma conversa conectada a serviços.', 'Estado de interface, mensagens assíncronas e feedback durante a resposta do webhook.', 'Integração n8n presente no cliente. OpenAI é descrito no README; workflow externo não versionado. Placar e torcida são simulados.'),
 'fan': ('Cadastro com etapas conectadas.', 'Formulário, upload documental e webhook organizados em uma jornada de identificação.', 'Protótipo com backend pendente de correções. A função Vercel e o fluxo completo não foram validados; não disponível como demo pública.'),
 'edp': ('Do pedido ao protocolo.', 'Validação de agências e registro estruturado de solicitações em Python.', 'MVP em revisão: conflitos de merge impedem executar a API atual. Atendimento em CLI não equivale a integração WhatsApp.'),
 'chronos': ('Fundamentos de frontend moderno.', 'Composição de interface com React, TypeScript e estilos modulares.', 'Estudo em desenvolvimento: contador estático, sem lógica de temporização ou histórico.'),
}

def visual(pid):
    if pid == 'pvt':
        return '<figure class="project-visual screenshot"><img src="images/pvt-dashboard.png" alt="Captura do PVT Dashboard: resumo de três projetos, tabela de horas e indicadores de saúde" width="1273" height="948" loading="lazy"><figcaption>Captura publicada no repositório · dados de demonstração</figcaption></figure>'
    if pid == 'retail':
        return '''<figure class="project-visual data-visual"><div class="visual-kicker">RETAIL / DATA EXPLORATION</div><div class="data-number">100.000<span>transações analisadas</span></div><div class="chart-row"><span>Internacionais</span><b>68,71%</b><i style="--value:68.71%"></i></div><div class="chart-row"><span>Domésticas</span><b>26,47%</b><i style="--value:26.47%"></i></div><figcaption>Taxa de fraude · recalculada a partir do CSV do projeto</figcaption></figure>'''
    flows = {
      'jungle': ('TRANSACTION DESIGN', ['HTTP / SQS', 'Idempotência + locks', 'Saldo · ledger · outbox'], 'Diagrama da arquitetura implementada'),
      'chat': ('CONVERSATIONAL INTERFACE', ['Mensagem em React', 'Webhook n8n', 'Resposta + estado da interface'], 'Fluxo observado no cliente · IA externa descrita no README'),
      'fan': ('SYSTEMS INTEGRATION', ['Formulário + documento', 'API → retorno ao cliente', 'Validação no cliente → n8n'], 'Fluxo previsto no código · backend com pendências'),
      'edp': ('PROCESS AUTOMATION', ['Solicitação', 'Validação + protocolo', 'Registro em Excel'], 'Fluxo do simulador CLI'),
      'chronos': ('FRONTEND FOUNDATIONS', ['React + TypeScript', 'Componentes + CSS Modules', 'Interface em desenvolvimento'], 'Estrutura implementada · temporizador ainda estático'),
    }
    label, nodes, caption = flows[pid]
    return '<figure class="project-visual flow-visual '+pid+'"><div class="visual-kicker">'+label+'</div><ol>'+''.join('<li>'+e(n)+'</li>' for n in nodes)+'</ol><figcaption>'+caption+'</figcaption></figure>'

def render(projects):
    head='''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Erick Ribeiro: engenharia de software com React, TypeScript, APIs, automação e dados. Explore projetos, código e decisões técnicas."><meta name="theme-color" content="#f5f3ed"><meta property="og:title" content="Erick Ribeiro — Software Engineer"><meta property="og:description" content="Interfaces, integrações e dados. Conheça os projetos e as decisões por trás do código."><title>{title}</title><link rel="icon" href="images/perfil-icon.png"><link rel="stylesheet" href="css/portfolio.css"><script src="js/portfolio.js" defer></script></head><body><a class="skip" href="#main">Pular para o conteúdo</a><header class="top"><a class="brand" href="index.html" aria-label="Erick Ribeiro, início">erick<span>ribeiro.</span></a><nav aria-label="Navegação principal"><a href="index.html#projects">Projetos</a><a href="index.html#about">Sobre</a><a href="blog.html">Blog</a><a class="nav-contact" href="mailto:erickribeirogon@gmail.com">Vamos conversar ↗</a></nav></header>'''
    footer='''<footer><span>© 2026 Erick Ribeiro · Software Engineering</span><a href="https://www.linkedin.com/in/erick-ribeiro-515992228/">LinkedIn ↗</a><a href="https://github.com/ErickRibGo">GitHub ↗</a><a href="#main">Voltar ao início ↑</a></footer></body></html>'''
    featured=[p for p in projects if p['featured']]
    cards=[]
    for i,p in enumerate(featured,1):
        title,detail,note=NOTES[p['id']]
        cards.append(f'''<article class="project project-{p['id']}" data-category="{p['id']}">{visual(p['id'])}<div class="project-body"><div class="card-top"><span class="eyebrow">0{i} / {e(p['category'])}</span><span class="status">{e(p['status'])}</span></div><h3>{e(p['name'])}</h3><p class="project-statement">{title}</p><p>{e(p['description'])}</p><p class="stack">{e(p['stack'])}</p><div class="card-links"><a href="cases.html#{p['id']}">{e(p['cta'])} →</a><a href="{BASE+p['repo']}" aria-label="Código de {e(p['name'])} no GitHub">Código ↗</a></div></div></article>''')
    cards.append(MMORPG_CARD)
    home=head.format(title='Erick Ribeiro — Software Engineer')+'''<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="tiny-square"></span>Software Engineer / Automation Engineer</p><h1>Interfaces claras.<br>Sistemas conectados.<br><em>Problemas resolvidos.</em></h1><p class="intro">Da experiência em React às APIs e automações em Python: software construído a partir do problema de negócio.</p><div class="hero-actions"><a class="button" href="#projects">Conheça meu trabalho <span>↓</span></a><a href="https://github.com/ErickRibGo">Explore o código ↗</a></div><div class="hero-stack" aria-label="Tecnologias demonstradas nos projetos"><span>React</span><span>TypeScript</span><span>Node.js</span><span>Python</span><span>SQL</span></div></div><aside class="hero-aside"><div class="portrait-frame"><img src="images/perfil_completo.jpg" alt="Erick Ribeiro" width="340" height="390"><span class="portrait-label">TECHNOLOGY / DATA / AI</span></div><p>Erick Ribeiro</p><span>Engenharia de software com visão de produto.</span></aside></section>
<div class="work-index"><span>UMA PONTA CONECTA A OUTRA</span><p>Frontend <b>→</b> APIs <b>→</b> Automação <b>→</b> Dados <b>→</b> Negócio</p></div>
<section id="projects"><div class="section-title"><div><p class="eyebrow">01 / Featured Projects</p><h2>Construir. Integrar.<br><em>Entender o resultado.</em></h2></div><p>Interfaces, arquitetura e análise.<br>Seis perspectivas sobre engenharia.</p></div><div class="project-filters" hidden role="group" aria-label="Filtrar projetos"><button type="button" data-filter="all" aria-pressed="true">Todos <span>06</span></button><button type="button" data-filter="pvt">Full Stack</button><button type="button" data-filter="jungle,mmorpg">Backend</button><button type="button" data-filter="retail">Data</button><button type="button" data-filter="chat,fan">IA & Integrações</button></div><p id="filter-status" class="sr-only" aria-live="polite"></p><div class="projects">'''+''.join(cards)+'''</div></section>
<section id="about" class="about"><div><p class="eyebrow">02 / Como penso software</p><h2>O código faz parte.<br><em>O contexto também.</em></h2><p class="intro">Meu trabalho conecta desenvolvimento web, integração de serviços e análise de dados. O portfólio reúne essas competências em projetos com problemas e decisões concretas.</p><a href="https://www.linkedin.com/in/erick-ribeiro-515992228/">Conheça meu perfil profissional ↗</a></div><div class="principles"><a href="cases.html#pvt"><span>01</span><div><h3>Transformar dados em uma interface útil</h3><p>No PVT, horas e marcos de entrega se tornam indicadores de saúde dos projetos.</p></div><b>↗</b></a><a href="cases.html#jungle"><span>02</span><div><h3>Tratar as regras como parte do sistema</h3><p>No Jungle, idempotência e transações coordenam os efeitos de cada operação.</p></div><b>↗</b></a><a href="cases.html#retail"><span>03</span><div><h3>Investigar antes de concluir</h3><p>No Retail, hipóteses são confrontadas com distribuições e padrões da base.</p></div><b>↗</b></a></div></section>
<section id="more" class="more"><div class="section-title"><div><p class="eyebrow">03 / Em evolução</p><h2>More Projects</h2></div><p>Automação operacional e estudos de frontend.</p></div>'''+''.join(f'<a class="more-row" href="cases.html#{p["id"]}"><span><strong>{e(p["name"])}</strong><small>{e(p["category"])} · {e(p["status"])}</small></span><span aria-hidden="true">↗</span></a>' for p in projects if not p['featured'])+'''</section><section class="contact-panel"><div><p class="eyebrow">Vamos conversar</p><h2>Um problema real.<br>Uma próxima construção.</h2><p>Conheça a implementação dos projetos ou entre em contato para conversar sobre oportunidades.</p></div><div class="contact-actions"><a class="button" href="mailto:erickribeirogon@gmail.com">Entrar em contato ↗</a><a href="https://github.com/ErickRibGo">Ver mais no GitHub ↗</a><button type="button" class="copy-email" hidden>Copiar e-mail</button><span class="copy-status" role="status"></span></div></section></main>'''+footer
    (ROOT/'index.html').write_text(home,encoding='utf-8')
    casehtml=head.format(title='Cases — Erick Ribeiro')+'''<main id="main" class="case-main"><p class="eyebrow">Decisões por trás do código</p><h1>Engenharia<br><em>em contexto.</em></h1><p class="intro">O problema, a implementação e o aprendizado técnico de cada projeto.</p><nav class="case-nav" aria-label="Índice dos cases">'''+''.join(f'<a href="#{p["id"]}">{e(p["name"])}</a>' for p in projects)+'<a href="#mmorpg">MMORPG em Python</a></nav>'
    for p in projects:
        title,detail,note=NOTES[p['id']]
        source_links=''.join(f'<li><a href="{BASE+p["repo"]}/blob/{p.get("branch","main")}/{s}">{e(s)}</a></li>' for s in p['sources'])
        casehtml+=f'''<article class="case" id="{p['id']}"><div class="case-heading"><div><p class="eyebrow">{e(p['category'])}</p><h2>{e(p['name'])}</h2></div><span class="status">{e(p['status'])}</span></div><p class="intro">{title} {detail}</p>{visual(p['id'])}<div class="case-facts"><div><span>FOCO</span><p>{e(p['skills'])}</p></div><div><span>TECNOLOGIAS</span><p>{e(p['stack'])}</p></div></div><dl><dt>O problema</dt><dd>{e(p['problem'])}</dd><dt>A implementação</dt><dd>{e(p['evidence'])}</dd><dt>Como as partes se conectam</dt><dd>{e(p['architecture'])}</dd></dl><div class="scope-note"><strong>Escopo atual</strong><p>{e(note)}</p></div><a class="button" href="{BASE+p['repo']}">Explorar código no GitHub ↗</a><details><summary>Referências de implementação</summary><ul>{source_links}</ul><p>Leitura do código público em 25/09/2026. A revisão não incluiu execução dos serviços externos ou da suíte de testes.</p></details></article>'''
    (ROOT/'cases.html').write_text(casehtml+MMORPG_CASE+'</main>'+footer,encoding='utf-8')
